@API_BITLIBRO_HostAddress= http://localhost:5188
@API_BIT_LIBRO_AccessTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwibmFtZSI6IkFkbWluIiwibmFtZWlkIjoiZWJmYjY2YWEtMzRjNC00NDBkLWIwYTEtOWFjNTUxMzI5YjBiIiwibGFzdG5hbWUiOiJTeXN0ZW0iLCJjaSI6IjEzMTEyMjAyMTEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0MjAwIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTE4OCIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc1MDE4ODc5NCwiZXhwIjoxNzUwMTkyMzk0LCJpYXQiOjE3NTAxODg3OTR9.xwUPv3udGu6SZEbaL6hW2HBK-Xe0YHn-3weWrnY2-fE
@API_BIT_LIBRO_AccessTokenEmployee=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtcGxveWVlQGV4YW1wbGUuY29tIiwibmFtZSI6IkVtcGxveWVlIDEiLCJuYW1laWQiOiJiYjExNzFkOS1iZjMxLTQwNDMtYjYzZS1iMjZjYjg3NDZhNDAiLCJsYXN0bmFtZSI6IkVtcGxveWVlIiwiY2kiOiIxMjM0NTY3ODkwIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDIwMCIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUxODgiLCJyb2xlIjoiRW1wbG95ZWUiLCJuYmYiOjE3NTAxODg4MjAsImV4cCI6MTc1MDE5MjQyMCwiaWF0IjoxNzUwMTg4ODIwfQ.RYhHJ6t2TqkjtAuF-ATP6QnYIt8svIc1M04J2UcvPcU

### login admin
POST {{API_BITLIBRO_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "Admin123!"
}

### login employee

POST {{API_BITLIBRO_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "employee@example.com",
  "password": "Admin123!"
}



### register employee (admin)

POST {{API_BITLIBRO_HostAddress}}/api/employee
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
    "email": "employee@example.com",
    "password": "Admin123!",
    "name":"Employee 1",
    "lastName":"Employee",
    "ci":"1234567890"
}

### get genres (admin)
GET {{API_BITLIBRO_HostAddress}}/api/genre
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}


### get employee (admin)
GET {{API_BITLIBRO_HostAddress}}/api/employee
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}