@API_BITLIBRO_HostAddress=http://localhost:5188
@API_BIT_LIBRO_AccessTokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwibmFtZSI6IkFkbWluIiwibmFtZWlkIjoiMTEzYjZjMmItMzlmNi00ZWIxLWI2NTMtYjEwYTk2MTRiMDFlIiwibGFzdG5hbWUiOiJTeXN0ZW0iLCJjaSI6IjEzMTEyMjAyMTEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0MjAwIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTE4OCIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc1NjAwODc1NCwiZXhwIjoxNzU2MDEyMzU0LCJpYXQiOjE3NTYwMDg3NTR9.wNqRjnlNBqVWjlG_MS6mS1nP9IjXVMlk9VuA9Wqlvf0
@API_BIT_LIBRO_AccessTokenEmployee=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtcGxveWVlQGV4YW1wbGUuY29tIiwibmFtZSI6IkVtcGxveWVlIDEiLCJuYW1laWQiOiJkNGEyN2YwNC1jYjlkLTQxMzctYTNlMC0wMjZkOTUwODk2YjgiLCJsYXN0bmFtZSI6IkVtcGxveWVlIiwiY2kiOiIxMjM0NTY3ODkwIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDIwMCIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjUxODgiLCJyb2xlIjoiRW1wbG95ZWUiLCJuYmYiOjE3NTAyNzA3MDksImV4cCI6MTc1MDI3NDMwOSwiaWF0IjoxNzUwMjcwNzA5fQ.aQ4ycndFFVO075rEJSc3B1HaHFJnctmXq_g7MYbj3-s


### 🧩 MÓDULO DE GÉNEROS
### [GET] Obtener todos los géneros paginados (admin)
GET {{API_BITLIBRO_HostAddress}}/api/genres?page=1&pageSize=10
Accept: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

### [GET] Obtener todos los géneros paginados error (employee)
GET {{API_BITLIBRO_HostAddress}}/api/genres?page=1&pageSize=10
Accept: application/json
Authorization: Bearer {{{{API_BIT_LIBRO_AccessTokenEmployee}}}}

### [GET] Género encontrado exitosamente (admin)
GET {{API_BITLIBRO_HostAddress}}/api/genres/2
Accept: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

### [GET] Género no encontrado (404)
GET {{API_BITLIBRO_HostAddress}}/api/genres/9999
Accept: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

### [POST] Género ya existente (409)
POST {{API_BITLIBRO_HostAddress}}/api/genres
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "name": "Acción"
}

### [POST] Errores de validación (nombre vacío)
POST {{API_BITLIBRO_HostAddress}}/api/genres
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "name": ""
}

### [POST] Creación exitosa
POST {{API_BITLIBRO_HostAddress}}/api/genres
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "name": "Ciencia Ficción"
}

### [PUT] Género ya en uso (409 - conflicto)
PUT {{API_BITLIBRO_HostAddress}}/api/genres/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "id":2,
  "name": "Acción"
}

### [PUT] Errores de validación (nombre vacío)
PUT {{API_BITLIBRO_HostAddress}}/api/genres/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "id":2,
  "name": ""
}

### [PUT] Actualización exitosa
PUT {{API_BITLIBRO_HostAddress}}/api/genres/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

{
  "id":2,
  "name": "Aventura"
}

### [DELETE] Eliminado exitosamente
DELETE {{API_BITLIBRO_HostAddress}}/api/genres/1
Accept: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

### [DELETE] Género no encontrado (404)
DELETE {{API_BITLIBRO_HostAddress}}/api/genres/9999
Accept: application/json
Authorization: Bearer {{API_BIT_LIBRO_AccessTokenAdmin}}

